name: Azure Container Apps Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v3

      # Step 2: Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Log in to ACR
      - name: Log in to Azure Container Registry
        run: |
          az acr login --name products19

      # Step 4: Build and Push the Docker Image
      - name: Build Docker Image
        run: |
          docker build -t products19.azurecr.io/my-app:latest .
      
      - name: Push Docker Image to ACR
        run: |
          docker push products19.azurecr.io/my-app:latest

      # Step 5: Deploy Container App
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: products19.azurecr.io/my-app:latest
          acrName: products19
          containerAppName: my-container-app
          resourceGroup: githubaction
