name: Azure Container Apps Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v3

      # Step 2: Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Create or Use Existing Environment
      - name: Create or Use Existing Environment
        run: |
          if ! az containerapp env show --name my-container-app-env --resource-group githubaction; then
            az containerapp env create \
              --name my-container-app-env \
              --resource-group githubaction \
              --location eastus
          fi

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t products19.azurecr.io/my-app:latest .

      # Step 5: Push Docker Image to ACR
      - name: Push Docker Image
        run: |
          docker push products19.azurecr.io/my-app:latest

      # Step 6: Deploy Container App
      - name: Deploy Azure Container App
        run: |
          if ! az containerapp show --name my-container-app --resource-group githubaction; then
            az containerapp create \
              --name my-container-app \
              --resource-group githubaction \
              --environment my-container-app-env \
              --image products19.azurecr.io/my-app:latest \
              --target-port 80 \
              --ingress external
          else
            az containerapp update \
              --name my-container-app \
              --resource-group githubaction \
              --image products19.azurecr.io/my-app:latest
          fi
