name: Build and Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ace-mile-379006

    - name: Authenticate Docker with GCP
      run: gcloud auth configure-docker us-docker.pkg.dev

    - name: Build Docker Image
      run: |
        docker build -t us-docker.pkg.dev/ace-mile-379006/gcr.io/your-image-name:$GITHUB_SHA .
        docker tag us-docker.pkg.dev/ace-mile-379006/gcr.io/your-image-name:$GITHUB_SHA us-docker.pkg.dev/ace-mile-379006/gcr.io/your-image-name:latest

    - name: Push Docker Image to Artifact Registry
      run: |
        docker push us-docker.pkg.dev/ace-mile-379006/gcr.io/your-image-name:$GITHUB_SHA
        docker push us-docker.pkg.dev/ace-mile-379006/gcr.io/your-image-name:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy your-service-name \
          --image us-docker.pkg.dev/ace-mile-379006/gcr.io/your-image-name:latest \
          --platform managed \
          --region us-east1 \
          --allow-unauthenticated
