name: Azure Container Apps Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v3

      # Step 2: Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Log in to Existing ACR
      - name: Log in to Azure Container Registry
        run: |
          az acr login --name products19

      # Step 4: Build and Push the Docker Image to Existing ACR
      - name: Build Docker Image
        run: |
          docker build -t products19.azurecr.io/my-app:latest .
      - name: Push Docker Image
        run: |
          docker push products19.azurecr.io/my-app:latest

      # Step 5: Deploy Azure Container App
      - name: Deploy Azure Container App
        run: |
          if ! az containerapp show --name my-container-app --resource-group githubaction; then
            az containerapp create \
              --name my-container-app \
              --resource-group githubaction \
              --environment managedEnvironment-WPIascexport-84f4 (WPI-asc-export) \
              --image products19.azurecr.io/my-app:latest \
              --target-port 7860 \
              --ingress external
          else
            az containerapp update \
              --name my-container-app \
              --resource-group githubaction \
              --image products19.azurecr.io/my-app:latest
          fi
